services:
  customerservicedb:
    image: mysql:latest
    container_name: customerservicedb
    environment:
      MYSQL_ROOT_PASSWORD: Prestige123
      MYSQL_DATABASE: customers_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - customerservicenetwork

  customerserviceapp:
    build: ./
    image: customerservices:1.0
    container_name: customerserviceapp
    ports:
      - "8080:8080"
    depends_on:
      - customerservicedb
    networks:
      - customerservicenetwork
    environment:
      - DATASOURCES_DEFAULT_URL=jdbc:mysql://customerservicedb:3306/customers_db
      - DATASOURCES_DEFAULT_USERNAME=root
      - DATASOURCES_DEFAULT_PASSWORD=Prestige123

networks:
  customerservicenetwork:
    driver: bridge

volumes:
  db_data:
