services:
  dbserver:
    image: mysql:latest
    container_name: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: Prestige123
      MYSQL_DATABASE: customers_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - customerservicenetwork

  customerserviceapp:
    build: ./
    image: customerservices:1.0
    container_name: customerserviceapp
    ports:
      - "8080:8080"
    depends_on:
      - dbserver
    environment:
      - DATASOURCES_DEFAULT_URL=jdbc:mysql://dbserver:3306/customers_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATASOURCES_DEFAULT_USERNAME=root
      - DATASOURCES_DEFAULT_PASSWORD=Prestige123
    networks:
      - customerservicenetwork

volumes:
  db_data:


networks:
  customerservicenetwork:
    name: customerservicenetwork
    driver: bridge
